[package]
name = "logmark"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true
autobins = false

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "logmark_app"
path = "src/main.rs"

[dependencies]
egui = { workspace = true, features = ["serde"] }
eframe.workspace = true
petgraph = { workspace = true, features = ["serde-1"] }
serde.workspace = true
serde_json.workspace = true
egui_graphs = { path = "../egui_graphs", features = ["events"] }
egui_commonmark = "0.22"
regex = "1.12"
ron = "0.12.0"
rfd = "0.16.0"
sublime_fuzzy = "0.7.0"
log = "0.4"
webbrowser = "1.0.6"
egui_code_editor = "0.2.20"
tree-sitter-markdown = "0.7.1"
tree-sitter-lua = "0.2.0"
tree-sitter = "0.19.5"

# WASM dependencies (only for wasm32 target)
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
	"Window", "Document", "HtmlCanvasElement", "Storage",
	"Url", "Blob", "BlobPropertyBag", "HtmlAnchorElement",
	"HtmlInputElement", "FileReader", "File", "FileList", "Event",
    "HtmlElement", "Node", "CssStyleDeclaration"
] }
console_error_panic_hook = "0.1"
getrandom = { version = "0.3", features = ["wasm_js"] }

[lints]
workspace = true
